#!/bin/bash

remote_user=calibre
remote_host=erficca.ins
remote_port=
remote_path=/home/calibre/propirata
local_path=/media/tera/backup/propirata
log_file=/media/tera/backup/propirata_archive.log
email=

### DO NOT MODIFY UNDER THIS LINE ###

date_string=`date +%F`

echo "" > $log_file

# copy remote archive in $local_path 
rsync -rhv --progress $remote_user@$remote_host:$remote_port$remote_path  $local_path &>> $log_file

# generate compressed archive
tar -cvf "$local_path"_"$date_string".tar.gz $local_path &>> $log_file

echo -e "Server: "$host" \n\n Autogenerated mail\n" > /tmp/void_mail.txt

if [ -z "$email" ]; then
	mutt -s "[$HOST] Archive Script Finished" -a $log_file < /tmp/void_mail.txt
fi
